export const pricingPlans = [
  {
    id: 1,
    parcelType: "Small Package",
    pickupLocation: "New York, NY",
    deliveryLocation: "Los Angeles, CA",
    weight: "1-5 kg",
    deliveryTime: "2-3 Days",
    price: "$9.99",
  },
  {
    id: 2,
    parcelType: "Medium Package",
    pickupLocation: "San Francisco, CA",
    deliveryLocation: "Chicago, IL",
    weight: "5-10 kg",
    deliveryTime: "3-4 Days",
    price: "$19.99",
  },
  {
    id: 3,
    parcelType: "Large Package",
    pickupLocation: "Miami, FL",
    deliveryLocation: "Dallas, TX",
    weight: "10-20 kg",
    deliveryTime: "5-7 Days",
    price: "$29.99",
  },
  {
    id: 4,
    parcelType: "Heavy Package",
    pickupLocation: "Seattle, WA",
    deliveryLocation: "Boston, MA",
    weight: "20-50 kg",
    deliveryTime: "7-10 Days",
    price: "$49.99",
  },
  {
    id: 5,
    parcelType: "Heavy Package",
    pickupLocation: "Seattle, WA",
    deliveryLocation: "Boston, MA",
    weight: "20-50 kg",
    deliveryTime: "7-10 Days",
    price: "$49.99",
  },
  {
    id: 6,
    parcelType: "Heavy Package",
    pickupLocation: "Seattle, WA",
    deliveryLocation: "Boston, MA",
    weight: "20-50 kg",
    deliveryTime: "7-10 Days",
    price: "$49.99",
  },
  {
    id: 7,
    parcelType: "Heavy Package",
    pickupLocation: "Seattle, WA",
    deliveryLocation: "Boston, MA",
    weight: "20-50 kg",
    deliveryTime: "7-10 Days",
    price: "$49.99",
  },
  {
    id: 8,
    parcelType: "Heavy Package",
    pickupLocation: "Seattle, WA",
    deliveryLocation: "Boston, MA",
    weight: "20-50 kg",
    deliveryTime: "7-10 Days",
    price: "$49.99",
  },
  {
    id: 9,
    parcelType: "Heavy Package",
    pickupLocation: "Seattle, WA",
    deliveryLocation: "Boston, MA",
    weight: "20-50 kg",
    deliveryTime: "7-10 Days",
    price: "$49.99",
  },
  {
    id: 10,
    parcelType: "Heavy Package",
    pickupLocation: "Seattle, WA",
    deliveryLocation: "Boston, MA",
    weight: "20-50 kg",
    deliveryTime: "7-10 Days",
    price: "$49.99",
  },
];
