export const districtsData = [
  {
    district: "Bagerhat",
    zones: [
      {
        zone: "Kachua",
        areas: [
          "Shonakhali",
          "Baintala",
          "Dhopakhali",
          "Shonakhali",
          "Baintala",
          "Dhopakhali",
          "Shonakhali",
          "Baintala",
          "Dhopakhali",
        ],
      },
      {
        zone: "Mongla",
        areas: [
          "Burirdanga",
          "Chandpai",
          "Mithakhali",
          "Burirdanga",
          "Chandpai",
          "Mithakhali",
          "Burirdanga",
          "Chandpai",
          "Mithakhali",
        ],
      },
    ],
  },
  {
    district: "Bandarban",
    zones: [
      {
        zone: "Bandarban Sadar",
        areas: [
          "Kuhalong",
          "Rajbila",
          "Sualok",
          "Kuhalong",
          "Rajbila",
          "Sualok",
          "Kuhalong",
          "Rajbila",
          "Sualok",
        ],
      },
      {
        zone: "Thanchi",
        areas: [
          "Remakri",
          "Tindu",
          "Thanchi Sadar",
          "Remakri",
          "Tindu",
          "Thanchi Sadar",
          "Remakri",
          "Tindu",
          "Thanchi Sadar",
        ],
      },
    ],
  },
  {
    district: "Chittagong",
    zones: [
      {
        zone: "Patiya",
        areas: [
          "Char Lakshya",
          "Kachuai",
          "Sikalbaha",
          "Char Lakshya",
          "Kachuai",
          "Sikalbaha",
          "Char Lakshya",
          "Kachuai",
          "Sikalbaha",
        ],
      },
      {
        zone: "Satkania",
        areas: [
          "Bazalia",
          "Dohazari",
          "Satkania Sadar",
          "Bazalia",
          "Dohazari",
          "Satkania Sadar",
          "Bazalia",
          "Dohazari",
          "Satkania Sadar",
        ],
      },
    ],
  },
  {
    district: "Dhaka",
    zones: [
      {
        zone: "Gulshan",
        areas: [
          "Gulshan 1",
          "Gulshan 2",
          "Baridhara",
          "Gulshan 1",
          "Gulshan 2",
          "Baridhara",
          "Gulshan 1",
          "Gulshan 2",
          "Baridhara",
        ],
      },
      {
        zone: "Mirpur",
        areas: [
          "Mirpur 10",
          "Mirpur 11",
          "Mirpur 12",
          "Mirpur 10",
          "Mirpur 11",
          "Mirpur 12",
          "Mirpur 10",
          "Mirpur 11",
          "Mirpur 12",
        ],
      },
    ],
  },
  {
    district: "Khulna",
    zones: [
      {
        zone: "Khulna Sadar",
        areas: [
          "Khan Jahan Ali",
          "Sonadanga",
          "Khalishpur",
          "Khan Jahan Ali",
          "Sonadanga",
          "Khalishpur",
          "Khan Jahan Ali",
          "Sonadanga",
          "Khalishpur",
        ],
      },
      {
        zone: "Dacope",
        areas: [
          "Bajua",
          "Kamarkhola",
          "Tildanga",
          "Bajua",
          "Kamarkhola",
          "Tildanga",
          "Bajua",
          "Kamarkhola",
          "Tildanga",
        ],
      },
    ],
  },
  {
    district: "Rajshahi",
    zones: [
      {
        zone: "Rajshahi Sadar",
        areas: [
          "Boalia",
          "Shah Makhdum",
          "Motihar",
          "Boalia",
          "Shah Makhdum",
          "Motihar",
          "Boalia",
          "Shah Makhdum",
          "Motihar",
        ],
      },
      {
        zone: "Paba",
        areas: [
          "Paba",
          "Bhabaniganj",
          "Haripur",
          "Paba",
          "Bhabaniganj",
          "Haripur",
          "Paba",
          "Bhabaniganj",
          "Haripur",
        ],
      },
    ],
  },
  {
    district: "Sylhet",
    zones: [
      {
        zone: "Sylhet Sadar",
        areas: [
          "Bandar Bazar",
          "Mirabazar",
          "Subidbazar",
          "Bandar Bazar",
          "Mirabazar",
          "Subidbazar",
          "Bandar Bazar",
          "Mirabazar",
          "Subidbazar",
        ],
      },
      {
        zone: "Beanibazar",
        areas: [
          "Beanibazar",
          "Lalbazar",
          "Kurarbazar",
          "Beanibazar",
          "Lalbazar",
          "Kurarbazar",
          "Beanibazar",
          "Lalbazar",
          "Kurarbazar",
        ],
      },
    ],
  },
  {
    district: "Rangpur",
    zones: [
      {
        zone: "Rangpur Sadar",
        areas: [
          "Kachari Bazar",
          "Kellaband",
          "Mithapukur",
          "Kachari Bazar",
          "Kellaband",
          "Mithapukur",
          "Kachari Bazar",
          "Kellaband",
          "Mithapukur",
        ],
      },
      {
        zone: "Pirganj",
        areas: [
          "Pirganj",
          "Mithapukur",
          "Badarganj",
          "Pirganj",
          "Mithapukur",
          "Badarganj",
          "Pirganj",
          "Mithapukur",
          "Badarganj",
        ],
      },
    ],
  },
  {
    district: "Barisal",
    zones: [
      {
        zone: "Barisal Sadar",
        areas: [
          "Nathullabad",
          "Kawnia",
          "Rupatoli",
          "Nathullabad",
          "Kawnia",
          "Rupatoli",
          "Nathullabad",
          "Kawnia",
          "Rupatoli",
        ],
      },
      {
        zone: "Bakerganj",
        areas: [
          "Bakerganj",
          "Charamandi",
          "Gournadi",
          "Bakerganj",
          "Charamandi",
          "Gournadi",
          "Bakerganj",
          "Charamandi",
          "Gournadi",
        ],
      },
    ],
  },
  {
    district: "Comilla",
    zones: [
      {
        zone: "Comilla Sadar",
        areas: [
          "Kandirpar",
          "Kotbari",
          "Shashongachha",
          "Kandirpar",
          "Kotbari",
          "Shashongachha",
          "Kandirpar",
          "Kotbari",
          "Shashongachha",
        ],
      },
      {
        zone: "Chauddagram",
        areas: [
          "Chauddagram",
          "Batisha",
          "Gouripur",
          "Chauddagram",
          "Batisha",
          "Gouripur",
          "Chauddagram",
          "Batisha",
          "Gouripur",
        ],
      },
    ],
  },
  {
    district: "Mymensingh",
    zones: [
      {
        zone: "Mymensingh Sadar",
        areas: [
          "Kewatkhali",
          "Shambhuganj",
          "Char Ishwardia",
          "Kewatkhali",
          "Shambhuganj",
          "Char Ishwardia",
          "Kewatkhali",
          "Shambhuganj",
          "Char Ishwardia",
        ],
      },
      {
        zone: "Trishal",
        areas: [
          "Trishal",
          "Balipara",
          "Mathbari",
          "Trishal",
          "Balipara",
          "Mathbari",
          "Trishal",
          "Balipara",
          "Mathbari",
        ],
      },
    ],
  },
  {
    district: "Jessore",
    zones: [
      {
        zone: "Jessore Sadar",
        areas: [
          "Chanchra",
          "Noapara",
          "Bagharpara",
          "Chancha",
          "Noapara",
          "Bagharpara",
          "Chancha",
          "Noapara",
          "Bagharpara",
        ],
      },
      {
        zone: "Monirampur",
        areas: [
          "Monirampur",
          "Keshabpur",
          "Jhikargachha",
          "Monirampur",
          "Keshabpur",
          "Jhikargachha",
          "Monirampur",
          "Keshabpur",
          "Jhikargachha",
        ],
      },
    ],
  },
  {
    district: "Pabna",
    zones: [
      {
        zone: "Pabna Sadar",
        areas: [
          "Pabna Sadar",
          "Sathia",
          "Bera",
          "Pabna Sadar",
          "Sathia",
          "Bera",
          "Pabna Sadar",
          "Sathia",
          "Bera",
        ],
      },
      {
        zone: "Ishwardi",
        areas: [
          "Ishwardi",
          "Pakshi",
          "Santhia",
          "Ishwardi",
          "Pakshi",
          "Santhia",
          "Ishwardi",
          "Pakshi",
          "Santhia",
        ],
      },
    ],
  },
  {
    district: "Noakhali",
    zones: [
      {
        zone: "Noakhali Sadar",
        areas: [
          "Maijdee",
          "Sonapur",
          "Kabirhat",
          "Maijdee",
          "Sonapur",
          "Kabirhat",
          "Maijdee",
          "Sonapur",
          "Kabirhat",
        ],
      },
      {
        zone: "Begumganj",
        areas: [
          "Begumganj",
          "Chatkhil",
          "Senbagh",
          "Begumganj",
          "Chatkhil",
          "Senbagh",
          "Begumganj",
          "Chatkhil",
          "Senbagh",
        ],
      },
    ],
  },
  {
    district: "Tangail",
    zones: [
      {
        zone: "Tangail Sadar",
        areas: [
          "Tangail Sadar",
          "Ghatail",
          "Kalihati",
          "Tangail Sadar",
          "Ghatail",
          "Kalihati",
          "Tangail Sadar",
          "Ghatail",
          "Kalihati",
        ],
      },
      {
        zone: "Mirzapur",
        areas: [
          "Mirzapur",
          "Gopalpur",
          "Basail",
          "Mirzapur",
          "Gopalpur",
          "Basail",
          "Mirzapur",
          "Gopalpur",
          "Basail",
        ],
      },
    ],
  },
  {
    district: "Bogra",
    zones: [
      {
        zone: "Bogra Sadar",
        areas: [
          "Bogra Sadar",
          "Sherpur",
          "Dhunat",
          "Bogra Sadar",
          "Sherpur",
          "Dhunat",
          "Bogra Sadar",
          "Sherpur",
          "Dhunat",
        ],
      },
      {
        zone: "Sariakandi",
        areas: [
          "Sariakandi",
          "Sonatala",
          "Dhunat",
          "Sariakandi",
          "Sonatala",
          "Dhunat",
          "Sariakandi",
          "Sonatala",
          "Dhunat",
        ],
      },
    ],
  },
  {
    district: "Dinajpur",
    zones: [
      {
        zone: "Dinajpur Sadar",
        areas: [
          "Dinajpur Sadar",
          "Birampur",
          "Birganj",
          "Dinajpur Sadar",
          "Birampur",
          "Birganj",
          "Dinajpur Sadar",
          "Birampur",
          "Birganj",
        ],
      },
      {
        zone: "Parbatipur",
        areas: [
          "Parbatipur",
          "Phulbari",
          "Birol",
          "Parbatipur",
          "Phulbari",
          "Birol",
          "Parbatipur",
          "Phulbari",
          "Birol",
        ],
      },
    ],
  },
];
